openapi: 3.0.0
info:
  title: minha outra API
  description: quarto exemplo de swagger yaml description
  version: 1.0.0

servers:
  - url: www.prod-meuexemplo.com/v1
    description: production access url
  - url: www.hmg-meuexemplo.com/v1
    description: homologação access url

paths:
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error